### ISSUE TITLE
Description field is badly formatted when there are code blocks or other formatting

### ISSUE THREAD

**Issue by direction** [abelmartin/pull-requester#37] opened 2013-09-10 15:48 UTC
Raw

[Finished #56523024] 

_Added a rspec matcher for ```has_serialized_hash``` but only added the tests for ```OfferDetail``` : feel free to add tests for the other call sites of ```has_serialized_hash```_

Current

![screen shot 2013-09-10 at 11 44 59 am](https://f.cloud.github.com/assets/10589/1115758/fde3b27e-1a2f-11e3-8157-d094ca96e345.jpeg)

Should look more like:

![screen shot 2013-09-10 at 11 45 49 am](https://f.cloud.github.com/assets/10589/1115765/17983e92-1a30-11e3-87e8-ad03649738f6.jpeg)

**Comment by abelmartin** [comment] 2013-09-10 15:52
The issue is you have content in a `<code>` tags smushed up next to text without any breaks.

The PR info column can't help you out in this case because `<code>` & `<pre>` blocks don't respect browser/css desired scrolling without wrapping them in other block-tags.

You can, however, scroll in the space. :smile:

**Comment by abelmartin** [comment] 2013-09-10 15:55
Hmm...actually...it's all wrapped in an `<em>`.  I'll see what i can do

**Comment by direction** [comment] 2013-09-10 16:02
Yes it's wrapped in an em but I think it should respect what Github is doing in that info space too for consistency.

**Comment by abelmartin** [comment] 2013-09-10 16:03
![screen shot 2013-09-10 at 12 03 42 pm](https://f.cloud.github.com/assets/29429/1115917/a129048c-1a32-11e3-8665-3e0e513202fe.png)

As soon as I removed the extraneous "_" wrapping the PR content, everything renders correctly.  I think this is going into the won't fix bucket I'm afraid, but please keep sending me anything you find. :smile:

**Comment by direction** [comment] 2013-09-10 16:04
It's not extraneous. It's mean to be wrapped in an em tag. look at the github screenshot i attached to see how github does it

**Comment by abelmartin** [comment] 2013-09-10 16:08
You're saying that your comment doesn't make sense unless it's italicized?

**Comment by direction** [comment] 2013-09-10 16:09
No i'm saying I chose to italicize it.

Pullrequester should handle the case when a comment is italicized and has code blocks in it which it currently doesn't like Github clearly does.

**Comment by abelmartin** [comment] 2013-09-10 16:11
Fine, @direction, fine.

Some people would just let things go...but noooooooo.  @direction needs to have her precious italicized content. :stuck_out_tongue: 

Reopening this horrible bug.

**Comment by direction** [comment] 2013-09-10 16:26
hahahaha @abelmartin just admit that there's a bug and file it. you can choose to NEVER fix it :smiling_imp:

**Closed as completed** 2013-09-10 18:18 UTC
Labels: bug
